# Generated by Django 4.0.2 on 2022-02-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generos',
            options={'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='generos',
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.generos')),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='jogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.jogo'),
            preserve_default=False,
        ),
    ]
