# Generated by Django 4.0.2 on 2022-02-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_generos_options_alter_transacao_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacao',
            new_name='Compra',
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={},
        ),
    ]
