# Generated by Django 4.0.2 on 2022-02-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_transacao_compra_alter_compra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
