# Generated by Django 4.0.2 on 2022-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_compra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
