# Generated by Django 4.0.2 on 2022-02-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_compra_observacoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
    ]
